valint:
  logger:
    level: debug
  cache:
    enable: false
  verify:
    # -- Evidence format
    input-format: statement
    # -- Policy result format
    formats: statement
  context:
    context-type: local
  attest:
    bundle: https://github.com/scribe-public/sample-policies
