project_name: gatekeeper-valint

env:
  - DESCRIPTION="Valint gatekeeper external data provider"
  - IMAGE_TAG={{ if index .Env "IsDev" }}dev-latest{{ else }}latest{{ end }}
  - BUCKET={{ if index .Env "IsDev" }}dev/{{ end }}
  - GO111MODULE=on

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy

builds:
  - id: main
    binary: '{{ tolower .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - darwin
    goarch:
      - amd64
      # - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags: |
      -w
      -s
      -extldflags '-static'
      -X {{ .ModulePath }}/cmd.version={{.Version}}

dockers:
  - dockerfile: docker/Dockerfile
    image_templates:
      # - "scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint:{{ .Env.IMAGE_TAG }}"
      - "scribesecurity/{{ tolower .ProjectName }}:{{ .Tag }}"
      - "scribesecurity/{{ tolower .ProjectName }}:{{ .Env.IMAGE_TAG }}"
    ids:
      - main
    goarch: amd64
    build_flag_templates:
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=DESCRIPTION={{.Env.DESCRIPTION}}"
      - "--build-arg=PROJECT_NAME={{.ProjectName}}"
      
    use: buildx
    skip_push: false
    extra_files:
      - docker/entrypoint.sh
