{{- if .Values.image.bundlePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-valint-bundle-pull-secret
  namespace: gatekeeper-valint
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  auth: {{ .Values.image.bundlePullSecrets }}
{{- end }}