apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-valint-certs
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  tls.crt: {{ .Values.certs.tlsCrt | quote }}
  tls.key: {{ .Values.certs.tlsKey | quote }}
type: kubernetes.io/tls
