apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-valint-certs
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  tls.crt: {{ required "certs.tlsCrt is required" .Values.certs.tlsCrt | quote }}
  tls.key: {{ required "certs.tlsKey is required" .Values.certs.tlsKey | quote }}
type: kubernetes.io/tls
