apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-valint-config
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.valint | toYaml | indent 4 }}
