{{- if .Values.select }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-valint-policies
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
data:
  map.yaml: |
{{ .Values.select | toYaml | indent 4 }}
{{- end }}