apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sExternalDataValint
metadata:
  name: gatekeeper-valint
spec:
  enforcementAction: deny
  match:
    namespaces:
      - {{ .Values.constraint.namespace }}
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
