apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sExternalDataValint
metadata:
  name: gatekeeper-valint
spec:
  enforcementAction: deny
  match:
    {{- if .Values.constraint }}
    namespaces:
    {{- if .Values.constraint.namespaces }}
    {{- range .Values.constraint.namespaces }}
    - {{ . }}
    {{- end }}
    {{- end }}
    {{- end }}
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
