apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-valint
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gatekeeper-valint
  template:
    metadata:
      labels:
        run: gatekeeper-valint
    spec:
      containers:
      - image: scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint:dev
        imagePullPolicy: IfNotPresent
        name: external-data-provider
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        args:
        - "--config=/valint/config.yaml"
        ports:
        - containerPort: 8090
          protocol: TCP
        env:
        - name: POLICIES_TMP_ROOT
          value: "/policies"
        - name: SIGSTORE_NO_CACHE
          value: "true"
        - name: DEBUG
          value: "true"
        - name: VALINT_SCRIBE_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: scribe-cred-secret
              key: scribe_client_id
        - name: VALINT_SCRIBE_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: scribe-cred-secret
              key: scribe_client_secret
        - name: VALINT_SCRIBE_ENABLE
          valueFrom:
            secretKeyRef:
              name: scribe-cred-secret
              key: scribe_enable
        volumeMounts:
        - name: valint-config
          mountPath: /valint
          readOnly: true
        - name: policies
          mountPath: /policies
          readOnly: false
      volumes:
        - name: valint-config
          configMap:
            name: valint-config
        - name: policies
          emptyDir:
            sizeLimit: 100Mi
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
