{{- if .Values.image.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-valint-pull-secret
  namespace: gatekeeper-valint
data:
  .dockerconfigjson: {{ .Values.image.imagePullSecrets }}
type: kubernetes.io/dockerconfigjson
{{- end }}