apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: gatekeeper-valint
  namespace: '{{ .Release.Namespace }}'
spec:
  url: https://gatekeeper-valint.{{ .Release.Namespace }}:{{  required "provider.port is required" .Values.provider.port }}/validate
  {{- if .Values.provider.timeout }}
  timeout: {{ regexReplaceAll "(.*)([a-zA-Z])$" .Values.provider.timeout "$1" }}
  {{- else }}
  timeout: 300
  {{- end }}
  caBundle: {{ required "certs.caBundle is required" .Values.certs.caBundle | quote }}
