apiVersion: externaldata.gatekeeper.sh/v1beta1
kind: Provider
metadata:
  name: gatekeeper-valint
  namespace: '{{ .Release.Namespace }}'
spec:
  url: https://gatekeeper-valint.{{ .Release.Namespace }}:{{ .Values.port }}/validate
  timeout: 300
  caBundle: {{ required "certs.caBundle is required" .Values.certs.caBundle | quote }}
