apiVersion: externaldata.gatekeeper.sh/v1alpha1
kind: Provider
metadata:
  name: gatekeeper-valint
spec:
  url: http://gatekeeper-valint.gatekeeper-valint:8090/validate
  timeout: 30
  insecureTLSSkipVerify: true
