apiVersion: v1
kind: Secret
metadata:
  name: valint-scribe-cred-secret
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  scribe_client_secret: {{ .Values.scribe.client_secret | quote }}
  scribe_enable: {{ .Values.scribe.enable | quote }}
  {{- if .Values.scribe.url }}
  scribe_url: {{ .Values.scribe.url | quote }}
  {{- end }}
