apiVersion: v1
kind: Secret
metadata:
  name: scribe-cred-secret
  namespace: '{{ .Release.namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  scribe_client_id: {{ .Values.scribe.client_id | quote }}
  scribe_client_secret: {{ .Values.scribe.client_secret | quote }}
  scribe_enable: {{ .Values.scribe.enable | quote }}
