apiVersion: v1
kind: Secret
metadata:
  name: scribe-cred-secret
  namespace: {{ .Release.Namespace }}
stringData:
  scribe_client_id: {{ .Values.scribe_client_id }}
  scribe_client_secret: {{ .Values.scribe_client_secret }}
  scribe_enable: {{ .Values.scribe_enable }}

