apiVersion: v1
kind: Secret
metadata:
  name: scribe-cred-secret
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  scribe_client_id: {{ .Values.scribeCredSecret.scribeClientId | quote }}
  scribe_client_secret: {{ .Values.scribeCredSecret.scribeClientSecret | quote }}
  scribe_enable: {{ .Values.scribeCredSecret.scribeEnable | quote }}
