apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-valint
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: gatekeeper-valint
  sessionAffinity: None
