apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
  name:  {{ include "gatekeeper-valint.serviceAccountName" . }}