apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-valint
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    run: gatekeeper-valint
  {{- include "gatekeeper-valint.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.provider.port }}
      protocol: TCP
      targetPort: {{ .Values.provider.port }}
