apiVersion: v1
kind: Secret
metadata:
  name: scribe-x509-secret
  namespace: '{{ .Release.namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  ATTEST_CERT: {{ .Values.x509.cert | quote }}
  ATTEST_CA: {{ .Values.x509.ca | quote }}
