apiVersion: v1
kind: Secret
metadata:
  name: scribe-x509-secret
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  ATTEST_CERT: {{ required "x509.cert is required" .Values.x509.cert | quote }}
  ATTEST_CA: {{ required "x509.ca is required" .Values.x509.ca | quote }}
