{{- if .Values.valint.config.verifier.x509.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-valint-verify-certs
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
data:
  cert.pem: {{ required "verify-certs.cert is required" .Values.verify-certs.cert | quote }}
  ca.pem: {{ required "verify-certs.ca is required" .Values.verify-certs.ca | quote }}
{{- end }}
