apiVersion: v1
kind: Secret
metadata:
  name: scribe-x509-secret
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
stringData:
  {{- if .Values.x509.cert }}
  ATTEST_CERT: {{ .Values.x509.cert | quote }}
  {{- end }}
  {{- if .Values.x509.key }}
  ATTEST_KEY: {{ .Values.x509.key | quote }}
  {{- end }}
  ATTEST_CA: {{ .Values.x509.ca | quote }}
