{{- if (((.Values.valint.config).verifier).x509).enable }}
apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-valint-verify-certs
  labels:
  {{- include "gatekeeper-valint.labels" . | nindent 4 }}
data:
  cert.pem: {{ required "verifyCerts.cert is required" .Values.verifyCerts.cert | quote }}
  ca.pem: {{ required "verifyCerts.ca is required" .Values.verifyCerts.ca | quote }}
{{- end }}
