apiVersion: v1
kind: ConfigMap
metadata:
  name: valint-config
  namespace: gatekeeper-valint
data:
  config.yaml: |
    logger:
      level: debug
    cache:
      enable: false
    verify:
      # -- Evidence format
      input-format: attest
    attest:
      # -- Signature verification type
      default: sigstore
      cocosign:
        storer:
          OCI:
            # -- OCI evidence enable
            enable: true
            # -- OCI evidence repo location 
            repo: ""
        policies:
          enable: true
          name: my_policy
          modules:
            - type: verify-artifact
              enable: true
              name: verify_rego
              input:
                rego:
                  args:
                    some: user_input
                  script: |
                    package verify

                    verify = v {
                      v := {
                        "allow": true
                      }
                    }

