apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-valint
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-valint
  namespace: gatekeeper-valint
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gatekeeper-valint
  template:
    metadata:
      labels:
        run: gatekeeper-valint
    spec:
      containers:
      - image: scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint:dev
        imagePullPolicy: Always
        name: gatekeeper-valint
        ports:
        - containerPort: 8090
          protocol: TCP
        args:
        - "--config=/valint/config.yaml"
        # - --port={{ .Values.port }}
        env:
        - name: POLICIES_TMP_ROOT
          value: "/policies"
        - name: SIGSTORE_NO_CACHE
          value: "true"
        - name: DEBUG
          value: "true"
        - name: VALINT_SCRIBE_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: scribe-cred-secret
              key: scribe_client_id
        - name: VALINT_SCRIBE_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: scribe-cred-secret
              key: scribe_client_secret
        - name: VALINT_SCRIBE_ENABLE
          valueFrom:
            secretKeyRef:
              name: scribe-cred-secret
              key: scribe_enable
        volumeMounts:
        - name: valint-config
          mountPath: /valint
          readOnly: true
        - name: valint-certs
          mountPath: /valint-certs
          readOnly: true
        - name: policies
          mountPath: /policies
          readOnly: false
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: valint-config
          configMap:
            name: valint-config
        - name: valint-certs
          secret:
            secretName: valint-certs
        - name: policies
          emptyDir:
            sizeLimit: 100Mi
