apiVersion: v1
kind: Secret
metadata:
  name: valint-certs
  namespace: gatekeeper-valint
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDYDCCAkigAwIBAgIUEpXWyJEaoi5LtKKEtOG2Vd2WB9IwDQYJKoZIhvcNAQEL
    BQAwMjETMBEGA1UECgwKR2F0ZWtlZXBlcjEbMBkGA1UEAwwSR2F0ZWtlZXBlciBS
    b290IENBMB4XDTIzMDkxMzEzMTAwNFoXDTIzMDkxNDEzMTAwNFowLjEsMCoGA1UE
    AwwjZ2F0ZWtlZXBlci12YWxpbnQuZ2F0ZWtlZXBlci12YWxpbnQwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCr7XfyeDGUqIMHraDVO7kuzQwVuBQ5M9Nr
    LHEY+6N7+mcDvcjjhrjNv/OQi43Vfi1zt2OfT0Je6zCWcY1kD7zKndYEfPmDNfqm
    2YNPXT14tVnSnvc+7ffkUEgnS7CLjUIsOc11RcJRRvaj9W9rfB+AYz0tG31gWniU
    YRg4LlKUJW3V/mGMA7+4z7XROwbNDdjEPeBBXa9H7EOXUcfwCCCuC3QL2fcW/0CJ
    0iz3nme1Vm4jZZexAvlJlBbQ0yLBUoj8pCbq8l0edxZhpwHKNSGn039VkZTme/Rc
    eU9oomMEqMRysew18iVu93uusJYiG4o6p0HqDEGsoI0SJAj58+X3AgMBAAGjcjBw
    MC4GA1UdEQQnMCWCI2dhdGVrZWVwZXItdmFsaW50LmdhdGVrZWVwZXItdmFsaW50
    MB0GA1UdDgQWBBTfnVPXFs2l2zvCPAsIepycPOR5hzAfBgNVHSMEGDAWgBTsvEkL
    YDtM6QRBHQ4a5fZvilKYwDANBgkqhkiG9w0BAQsFAAOCAQEAdvS254F4nwfzLmKR
    DHDbEVz19IgQsI/U35M114QBe3IFM2FpzLZ+7jvIxnm+Hsv7t4KxF6YsIzaoaMew
    /XoIaEvytdDIJlOS9bqwBqC0ehINT5OHzje77LgZa5Ns/ymTvmU30lBMQ/QV2E5+
    x6I0fp3TNnnXNBr8Ni751KuSi93h86+Yvwsk7+vIaIfBYVAbNRmUkSxT9tDhrXxW
    iSWT4DENp6e1SY4ST6FqwlODJhMTeJsVedJQTbLtKroqUsJB8VqCCWXZS9iYPVyr
    LmCeoMRLYYMagw9jw4koHyPy18FDwTWPIuHUqNhFFlAflBIjhxtjhzA7TmjtGeqQ
    bmHrFw==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCr7XfyeDGUqIMH
    raDVO7kuzQwVuBQ5M9NrLHEY+6N7+mcDvcjjhrjNv/OQi43Vfi1zt2OfT0Je6zCW
    cY1kD7zKndYEfPmDNfqm2YNPXT14tVnSnvc+7ffkUEgnS7CLjUIsOc11RcJRRvaj
    9W9rfB+AYz0tG31gWniUYRg4LlKUJW3V/mGMA7+4z7XROwbNDdjEPeBBXa9H7EOX
    UcfwCCCuC3QL2fcW/0CJ0iz3nme1Vm4jZZexAvlJlBbQ0yLBUoj8pCbq8l0edxZh
    pwHKNSGn039VkZTme/RceU9oomMEqMRysew18iVu93uusJYiG4o6p0HqDEGsoI0S
    JAj58+X3AgMBAAECggEAVV2dE4cLczkyijLzazzyx2Knb/dND1QE0y+nXlS/yXS9
    BpYKs7J2ey6mhKxOOeWjMtQpgnYLye50Wxa5sifAQUiadfMJvtUkBgl1UghFV/SP
    y20D7bqhvbsBAIXr/Hagly4CLor7H3khSKq6bn+ccpaTzxxZpeh1+5K0QFz7wrN8
    LM7QHAQ89DLKTGZ5ptRIEKVILKUQIlAYAopTWIMMhPz2U7IsQctuLE3qn5IjZtTE
    9Ovst4PV0sdawfBovQNgffaJczt1rSYI2iow7j1ocbyt2i+iXJCEvbLUyroZRgZj
    NmC0GbEswh6QhgWYuBT8JhP0Y0zT8QXr1nQ2mMF2VQKBgQDEj5cbE/Yamz70GyfY
    wvIaoM+ykG0ZGfvj0/7WzxyBM2j9ROQ+kOOktoyA2WWFLo6hMQz447IaI2/fflPu
    599xIhRye1zHwveZ5127KfQnq4iSZTe3gA+Mp5kJhBI7ouytu+qpnzjYbNG/+5U9
    QHqYy3fGYHHGCkAolm3f0RI4awKBgQDf6u+7KczeCt8K27OB5IkYtY0xLEZSAAJI
    84Lqn68i6SjxKSlCN+c8zuzEPyHapdaox68IG5noSCVMK/djGpekzmcJU+2b/hME
    sPxo0Sk5ZrbTiXkKt5HerueDyHJmf6r3z1IMTnRNeWMEVgivOr3reXeMsZYdYypR
    p37gzVbbpQKBgE2XGODZelZ6XdliNtJ78bHNNO+Zz1cPSL1gW8JTsz7VGmaPoUGJ
    VDMa1E+wgUCXZjn+8M32o8Fpp6mjZmJyKWOxPj0KsU8xiSe5iuhs4TIfpiOTzPCk
    nn65UdHNzpy37ZGPEkyuy3OzUQDlwL2TDFHwT3GBdKfmN/lNmEW3c+fNAoGBAIxF
    Yb6O1f73Mnhb31zsrJGlEfkO8lJmHQhUO9v9ArrM80/36BfKa3plal8Z6XxOTWXY
    Cab7m3Ou1macWFJmEz8z6conIH+LL6DNuqFy/e8ukDN+OCxliOTGDtQ4WqopKhIp
    dw2sjCEIfOX3e2NCWj1MD388tHxeZeFXGx16pQHdAoGBAKaI0fzwD4x3vQtYw8O6
    HAFHcWD22z+5Y/4vkVsoYcIBObE9PDV/Y8QSxsVah7LaAxgzcO+XY0+0Y5D1kcmo
    yTNMDLm2ISOPI4UGQU1rLQmgRTEFsrIHKVHwHIXD7o0S2JQY55sH5imO3+SIns4E
    bNSMdv/eZqBF9S4qWzM4PEvS
    -----END PRIVATE KEY-----

