apiVersion: v2
description: A Helm chart for a Valint GateKeeper provider
name: gatekeeper-valint
version: v1.2.0-6b
home: https://github.com/scribe-security/gatekeeper-valint
sources:
  - https://github.com/scribe-security/gatekeeper-valint.git
appVersion: v1.2.0-6

