image:
  repository: scribesecurity/gatekeeper-valint
  tag: v1.5.11
  imagePullPolicy: Always
certs:
  caBundle: ""
  tlsCrt: ""
  tlsKey: ""

serviceAccount:
  create: true

provider:
  port: 8090
  timeout: 28s #In seconds

replicas: 1

gatekeeperValint:
  debug: "true"
  sigstoreNoCache: "true"
  nodeSelector:
    kubernetes.io/os: linux

constraint:
  namespaces:
  - "default"

scribe:
  # -- Scribe Client Secret
  client_secret: ""
  # -- Scribe Client Enable
  #enable: false
  disable: false

x509:
  cert: "" 
  ca: ""

# Example of issuing Supply Chain Policies for specific resources.
# By Default the Signature Policy is Run on all images set to warning.
select:
  # -- Gate name
  gate: default_gate
  # -- Set all rules as warning
  warning: false
  # -- Run policy dry run mode
  dry-run: false
  # -- Use repo digest when image is not accessible
  target-fallback-repo-digest: false

  # -- Policy Select List
  apply:
  # -- Select Namespace that should comply to policy
  - namespace: "" # Any
    # -- Select Image Regular expression should comply to policy
    glob: 
    - "**"  # Any
    # -- filter evidence by scope, options<product, pipeline, target>
    filter-by:
    - target
    # -- Select policy rules and arguments to evaluate
    policy:
      # -- Policy name
      name: default-provider-policy
      rules:
      - name: warn_on_unsigned_image
        uses: sbom/artifact-signed@v1
        level: "warning"

valint:
  logger:
    level: info
  cache:
    enable: false
  verify:
    # -- Evidence format
    # input-format: statement
    # -- Policy result format
    formats: statement
  context:
    context-type: admission
  attest:
    bundle: https://github.com/scribe-public/sample-policies
    report:
      add-passed: true
    # -- Default verify with sigstore
    default: sigstore
    # bundle-args:
      # branch: