image:
  repository: scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint
  tag: dev
  imagePullPolicy: Always
certs:
  caBundle: ""
  tlsCrt: ""
  tlsKey: ""

port: 8090

replicas: 1

gatekeeperValint:
  debug: "true"
  sigstoreNoCache: "true"
  nodeSelector:
    kubernetes.io/os: linux

constraint:
  namespace: "default"

scribe:
  # -- Scribe Client ID
  client_id: ""
  # -- Scribe Client Secret
  client_secret: ""
    # -- Scribe Client Enable
  enable: false

x509:
  cert: "" 
  ca: ""

policies:
  - glob: "**"
    policies:
     - name: application-policy
       rules:
       - name: fresh-image
         uses: policies/images/fresh-image.yaml
         with:
          max_days: 400
valint:
  logger:
    level: debug
  cache:
    enable: false
  verify:
    # -- Evidence format
    input-format: statement
    # -- Policy result format
    formats: statement
  context:
    context-type: local
  attest:
    bundle: https://github.com/scribe-public/sample-policies

