image:
  repository: ghcr.io/scribe-security/gatekeeper-valint
  tag: v2.0.4
  imagePullPolicy: Always
certs:
  caBundle: ""
  tlsCrt: ""
  tlsKey: ""

serviceAccount:
  create: true

provider:
  port: 8090
  timeout: 29s #In seconds

replicas: 1

gatekeeperValint:
  debug: "true"
  sigstoreNoCache: "true"
  nodeSelector:
    kubernetes.io/os: linux

constraint:
  namespaces:
  - "default"

scribe:
  # -- Scribe Client Secret
  client_secret: ""
  # -- Scribe Client Enable
  #enable: false
  disable: false

x509:
  cert: "" 
  ca: ""

# Example of issuing Supply Chain Policies for specific resources.
# By Default the Signature Policy is Run on all images set to warning.
select:
  # -- Gate name
  gate-name: Scribe Admission Gate
  gate-type: admission

  # -- Set all rules as warning
  warning: true
  # -- Run policy dry run mode
  dry-run: false
  # -- Use repo digest when image is not accessible
  target-fallback-repo-digest: true

  # -- Policy Select List
  apply:
  # -- Select Namespace that should comply to policy
  - namespace: "" # Any
    # -- Select Image Regular expression should comply to policy
    glob: 
    - "**"  # Any
    # -- filter evidence by scope, options<product, pipeline, target>
    filter-by:
    - target
    # - product
    # -- Evaluate initiative by ref
    # initiative-ref: sp-800-190@v2

    # -- Evaluate custom initiative 
    # initiative:
    #   config-type: initiative
    #   id: "admission-initiative"
    #   version: "1.0.0"
    #   name: "Custom Admission Initiative"
    #   controls:
    #     - id: "admission-control"
    #       name: "Admission Control"
    #       description: "Custom control for admission policies"
    #       rules:
    #         - uses: sbom/artifact-signed@v2
    #           name: "warn on unsigned artifacts"
    #           level: error
              

valint:
  logger:
    level: info
  cache:
    enable: false
  verify:
    # -- Evidence format
    # input-format: statement
    # -- Policy result format
    formats: statement
  context:
    context-type: admission
  attest:
    bundle: https://github.com/scribe-public/sample-policies
    report:
      add-passed: true
    # -- Default verify with sigstore
    default: sigstore
    # bundle-args:
      # branch: