image:
  repository: scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint
  tag: dev
  imagePullPolicy: Always
certs:
  caBundle: ""
  tlsCrt: ""
  tlsKey: ""

serviceAccount:
  create: true

provider:
  port: 8090
  timeout: 300s #In seconds


replicas: 1

gatekeeperValint:
  debug: "false"
  sigstoreNoCache: "true"
  nodeSelector:
    kubernetes.io/os: linux

constraint:
  namespace: "default"

scribe:
  # -- Scribe Client ID
  client_id: ""
  # -- Scribe Client Secret
  client_secret: ""
    # -- Scribe Client Enable
  enable: false

x509:
  cert: "" 
  ca: ""

# Example of issuing Supply Chain Policies for specific resources.
# By Default the Signature Policy is Run on all images.
select:
  gate: my_gate
  warning: false
  dry-run: false
  apply:
  - namespace: "" # Any
    glob: 
    - "**"  # Any
    product-key: "prometheus-community/prometheus"
    filter-by: 
    - product
    policy:
      name: product-fullkit
      rules:
      - name: trivy-report-in-product
        uses: sarif/verify-tool-evidence@v1
        evidence:
          tool: "Trivy Vulnerability Scanner"

  - namespace: "" # Any
    glob: 
    - "**"  # Any
    product-key: "prometheus-community/prometheus"
    filter-by: 
    - product
    - target
    policy:
      name: target-policy
      rules:
        - name: evidence-exists-pipeline
          uses: sboms/evidence-exists@v1

        - name: fresh-image
          uses: images/fresh-image@v1
          level: warn
          with:
            max_days: 356

    #################### TYPES OF POLICIES #########################
    # - namespace: "" # Any
    #   glob: 
    #   - "**"  # Any
    #   product-key: "my_product"
    #   # workflow: "my_workflow"
    #   filter-by: 
    #   - product
    #   policy:
    #     name: product-fullkit
    #     rules:
    #     - name: trivy-report-in-product
    #       uses: sarif/verify-tool-evidence@v1
    #       evidence:
    #         tool: "Trivy Vulnerability Scanner"

    # - namespace: "" # Any
    #   glob: 
    #   - "**"  # Any
        # workflow: "my_workflow"

    #   filter-by: 
    #   - pipeline
    #   policy:
    #     name: pipeline-fullkit
    #     rules:

    #     - name: trivy-report-in-pipeline
    #       uses: sarif/verify-tool-evidence@v1
    #       evidence:
    #         tool: "Trivy Vulnerability Scanner"

    # - namespace: "" # Any
    #   glob: 
    #   - "**"  # Any
    #   filter-by: 
    #   - target
    #   policy:
    #     name: target-policy
    #     rules:
    #     - name: evidence-exists-pipeline
    #       uses: sboms/evidence-exists@v1

    #     - name: fresh-image
    #       uses: images/fresh-image@v1
    #       level: warn
    #       with:
    #         max_days: 356

valint:
  logger:
    level: info
  cache:
    enable: false
  verify:
    # -- Evidence format
    # input-format: statement
    # -- Policy result format
    formats: statement
  context:
    context-type: admission
  attest:
    bundle: https://github.com/scribe-public/sample-policies
    report:
      add-passed: true
  git:
    branch: dev
