image:
  repository: scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint
  tag: dev
  imagePullPolicy: Always
certs:
  caBundle: ""
  tlsCrt: ""
  tlsKey: ""

serviceAccount:
  create: true

provider:
  port: 8090
  timeout: 300s #In seconds


replicas: 1

gatekeeperValint:
  debug: "true"
  sigstoreNoCache: "true"
  nodeSelector:
    kubernetes.io/os: linux

constraint:
  namespace: "default"

scribe:
  # -- Scribe Client ID
  client_id: ""
  # -- Scribe Client Secret
  client_secret: ""
    # -- Scribe Client Enable
  enable: false

x509:
  cert: "" 
  ca: ""

# select:
#   gate: some_gate
#   apply:
#   - glob: 
#     - "**alpine**"
#     policies:
#     - name: application-policy
#       rules:
#       - name: fresh-image
#         uses: images/fresh-image@v1
#         with:
#           max_days: 400
    
#   - glob: 
#     - "nginx"
#     policies:
#     - name: framework-policy
#       rules:
#       - name: fresh-image
#         uses: images/fresh-image@v1
#         with:
#           max_days: 500 

valint:
  logger:
    level: debug
  cache:
    enable: false
  verify:
    # -- Evidence format
    input-format: statement
    # -- Policy result format
    formats: statement
  context:
    context-type: admission
  attest:
    bundle: https://github.com/scribe-public/sample-policies
    report:
      add-passed: true
