image:
  repository: scribesecuriy.jfrog.io/scribe-docker-public-local/gatekeeper-valint
  tag: dev
  imagePullPolicy: Always

certs:
  caBundle: ""
  tlsCrt: ""
  tlsKey: ""

port: 8090

replicas: 1

gatekeeperValint:
  debug: "true"
  sigstoreNoCache: "true"
  nodeSelector:
    kubernetes.io/os: linux

scribeCredSecret:
  scribeClientId: ""
  scribeClientSecret: ""
  scribeEnable: ""

constraint:
  namespace: "default"

verifyCerts:
  cert: ""
  ca: ""
