name: Remove old artifacts

on:
  schedule:
    # # Runs at 03:00 AM (UTC) every Monday, Wednesday, and Friday
    - cron: "0 3 * * 1,3,5" 
  workflow_dispatch:
  
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '2 day'
        # Optional inputs
        skip-tags: true
        skip-recent: 2
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '5 days'
          # Optional inputs
          # skip-tags: true
        skip-recent: 2
    - name: Clear caches
      uses: easimon/wipe-cache@main
      with:
        dry-run: 'false'