
name: dev-release

on:
  push:
    tags:
      - "*-*"
  workflow_dispatch:
  # pull_request:

concurrency: 
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-release:
    uses: ./.github/workflows/reusable_release.yml
    secrets:
      READ_PRIVATE_GO_REPOS: ${{ secrets.READ_PRIVATE_GO_REPOS }} ## needed to pull our private go libraries
      RELEASE_GITHUB_TOKEN: ${{ secrets.GHCR_GITHUB_RELEASE }}
    with:
      GITHUB_USER: houdini91
      IS_DEV: true
