
name: release

on:
  push:
    tags:
      - "*"
      - '!*-*'
  workflow_dispatch:

concurrency: 
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  call-release:
    uses: ./.github/workflows/reusable_release.yml
    secrets:
      RELEASE_GITHUB_TOKEN: ${{ secrets.READ_PRIVATE_GO_REPOS }} ## needed to pull our private go libraries
      RELEASE_ARTIFACTORY_TOKEN: ${{ secrets.RELEASE_ARTIFACTORY_TOKEN }}
      RELEASE_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      RELEASE_ARTIFACTORY_USERNAME: mikey@scribesecurity.com
      GITHUB_USER: houdini91
      RELEASE_DOCKERHUB_USERNAME: scribesecurity
