
name: release

on:
  push:
    tags:
      - "*"
      - '!*-*'
  workflow_dispatch:

concurrency: 
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-e2e-test:
    uses: ./.github/workflows/reusable_e2e.yml
    secrets:
      RELEASE_GITHUB_TOKEN: ${{ secrets.READ_PRIVATE_GO_REPOS }} ## needed to pull our private go libraries
      RELEASE_ARTIFACTORY_TOKEN: ${{ secrets.RELEASE_ARTIFACTORY_TOKEN }}
      SCRIBE_CLIENT_ID: ${{ github.event.inputs.SCRIBE_CLIENT_ID || secrets.SCRIBE_PROD_M2M_CLIENT_ID }}
      SCRIBE_CLIENT_SECRET: ${{ github.event.inputs.SCRIBE_CLIENT_SECRET || secrets.SCRIBE_PROD_M2M_CLIENT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.VALINT_SLACK_WEBHOOK_URL }}
    with:
      RELEASE_ARTIFACTORY_USERNAME: mikey@scribesecurity.com
      GITHUB_USER: houdini91
      SCRIBE_URL: https://airflow.scribesecurity.com
      SCRIBE_LOGIN_URL: https://scribe-hub-production.us.auth0.com
      SCRIBE_AUDIENCE:  api.production.scribesecurity.com
      ENV: production
      # reusable_e2e default is dev
      
  call-release:
    needs: call-e2e-test
    uses: ./.github/workflows/reusable_release.yml
    secrets:
      RELEASE_GITHUB_TOKEN: ${{ secrets.READ_PRIVATE_GO_REPOS }} ## needed to pull our private go libraries
      RELEASE_ARTIFACTORY_TOKEN: ${{ secrets.RELEASE_ARTIFACTORY_TOKEN }}
    with:
      RELEASE_ARTIFACTORY_USERNAME: mikey@scribesecurity.com
      GITHUB_USER: houdini91
