
name: staging_e2e

on:
  # push:
    # tags:
    #   - "*"
    # branches:
    #   - "pre-release/**"
    #   - "release/**"
    #   - "feature/policy-flow-readyness-pass1"
  pull_request:
  workflow_dispatch:
    inputs:
      SCRIBE_CLIENT_SECRET:
        description: 'Scribe client secret, default secret.SCRIBE_DEV_M2M_CLIENT_SECRET'
        required: false
        default: ''

concurrency: 
  group: e2e-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-e2e-test:
    uses: ./.github/workflows/reusable_e2e.yml
    secrets:
      READ_PRIVATE_GO_REPOS: ${{ secrets.READ_PRIVATE_GO_REPOS }} ## needed to pull our private go libraries
      RELEASE_GITHUB_TOKEN: ${{ secrets.GHCR_GITHUB_RELEASE }}
      SCRIBE_CLIENT_SECRET: ${{ github.event.inputs.SCRIBE_CLIENT_SECRET || secrets.SCRIBE_STAGING_M2M_CLIENT_SECRET }}
    with:
      GITHUB_USER: houdini91
      SCRIBE_URL: https://api.staging.scribesecurity.com
      ENV: dev
      DEBUG: true